import { useState, useCallback } from 'react';
import { getArtifactUrl } from '../../services/registrationApi';
import './ResultViewer.css';

/**
 * Artifact metadata definitions matching backend API specifications.
 */
const ARTIFACTS = [
  {
    id: 'registered',
    label: 'Registered Output',
    endpointType: 'registered',
    badge: 'Output Canvas',
    description:
      'Warped target lunar imagery resampled to the reference coordinate system via estimated matrix coefficients.',
  },
  {
    id: 'matches',
    label: 'Matches',
    endpointType: 'matches',
    badge: 'Putative Matches',
    description:
      'Candidate feature correspondence lines connecting detected SIFT keypoints across reference and target frames.',
  },
  {
    id: 'inliers',
    label: 'Inliers/Outliers',
    endpointType: 'inliers',
    badge: 'Geometric Verification',
    description:
      'Correspondence pairs classified by MAGSAC++: geometrically verified inliers (green) vs rejected outliers (red).',
  },
  {
    id: 'overlay',
    label: 'Overlay',
    endpointType: 'overlay',
    badge: 'Checkerboard Co-Registration',
    description:
      'Alternating checkerboard blocks between reference mosaic and warped target image to visually assess co-registration accuracy.',
  },
];

/**
 * ResultViewer — Stage B Classical Registration Diagnostic Visualizer.
 *
 * Renders the 4 diagnostic artifact images generated by POST /register:
 * 1. Registered Output (GET /register/{id}/registered)
 * 2. Matches (GET /register/{id}/matches)
 * 3. Inliers/Outliers (GET /register/{id}/inliers)
 * 4. Overlay (GET /register/{id}/overlay)
 *
 * Features:
 * - Tabbed focus view and side-by-side 2x2 comparison grid view
 * - Independent per-image loading state
 * - Independent per-image error state with retry (isolated from other tabs)
 * - Image download and open in full resolution
 *
 * @param {object} props
 * @param {string} props.resultId - UUID string of the successful registration.
 * @param {object} [props.metrics] - Optional metrics summary from registration response.
 */
export default function ResultViewer({ resultId, metrics = null }) {
  const [activeTab, setActiveTab] = useState('registered');
  const [viewMode, setViewMode] = useState('tab'); // 'tab' | 'grid'
  const [imageStates, setImageStates] = useState(() => {
    const initial = {};
    ARTIFACTS.forEach((art) => {
      initial[art.id] = { status: 'loading', retryKey: 0, errorMsg: '' };
    });
    return initial;
  });
  const [fitMode, setFitMode] = useState('contain'); // 'contain' | 'original'

  const handleImageLoad = useCallback((artId) => {
    setImageStates((prev) => ({
      ...prev,
      [artId]: { ...prev[artId], status: 'loaded', errorMsg: '' },
    }));
  }, []);

  const handleImageError = useCallback((artId) => {
    setImageStates((prev) => ({
      ...prev,
      [artId]: {
        ...prev[artId],
        status: 'error',
        errorMsg: `Failed to retrieve ${artId} artifact from backend. Image may be unavailable or still generating.`,
      },
    }));
  }, []);

  const handleRetry = useCallback((artId) => {
    setImageStates((prev) => ({
      ...prev,
      [artId]: {
        ...prev[artId],
        status: 'loading',
        retryKey: (prev[artId]?.retryKey || 0) + 1,
        errorMsg: '',
      },
    }));
  }, []);

  const getImageUrl = (art) => {
    if (!resultId) return '';
    const base = getArtifactUrl(resultId, art.endpointType);
    const retryKey = imageStates[art.id]?.retryKey || 0;
    return retryKey > 0 ? `${base}?retry=${retryKey}` : base;
  };

  const activeArtifact = ARTIFACTS.find((a) => a.id === activeTab) || ARTIFACTS[0];

  const renderImagePane = (art, isGrid = false) => {
    const state = imageStates[art.id] || { status: 'loading', retryKey: 0, errorMsg: '' };
    const url = getImageUrl(art);
    const isLoading = state.status === 'loading';
    const isError = state.status === 'error';

    return (
      <div
        key={art.id}
        className={`artifact-pane ${isGrid ? 'grid-pane' : 'tab-pane'} ${
          isError ? 'has-error' : ''
        }`}
      >
        {isGrid && (
          <div className="grid-pane-header">
            <div className="grid-pane-title-group">
              <span className="grid-pane-label">{art.label}</span>
              <span className="grid-pane-badge">{art.badge}</span>
            </div>
            <div className="grid-pane-actions">
              <button
                type="button"
                className="pane-icon-btn"
                onClick={() => {
                  setActiveTab(art.id);
                  setViewMode('tab');
                }}
                title="Expand to tab view"
                aria-label={`Expand ${art.label}`}
              >
                <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <polyline points="15 3 21 3 21 9" />
                  <polyline points="9 21 3 21 3 15" />
                  <line x1="21" y1="3" x2="14" y2="10" />
                  <line x1="3" y1="21" x2="10" y2="14" />
                </svg>
              </button>
              <a
                href={url}
                target="_blank"
                rel="noreferrer"
                className="pane-icon-btn"
                title="Open in new window"
                aria-label={`Open ${art.label} in new tab`}
              >
                <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6" />
                  <polyline points="15 3 21 3 21 9" />
                  <line x1="10" y1="14" x2="21" y2="3" />
                </svg>
              </a>
            </div>
          </div>
        )}

        <div className={`artifact-viewport ${fitMode === 'original' ? 'fit-original' : 'fit-contain'}`}>
          {isLoading && (
            <div className="pane-loader" aria-live="polite">
              <div className="pane-spinner" />
              <p className="pane-loading-text">Retrieving {art.label}…</p>
            </div>
          )}

          {isError ? (
            <div className="pane-error-card" role="alert">
              <div className="pane-error-icon">
                <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <circle cx="12" cy="12" r="10" />
                  <line x1="12" y1="8" x2="12" y2="12" />
                  <line x1="12" y1="16" x2="12.01" y2="16" />
                </svg>
              </div>
              <h5 className="pane-error-title">{art.label} Unavailable</h5>
              <p className="pane-error-msg">{state.errorMsg}</p>
              <button
                type="button"
                className="pane-retry-btn"
                onClick={() => handleRetry(art.id)}
              >
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <polyline points="1 4 1 10 7 10" />
                  <path d="M3.51 15a9 9 0 1 0 2.13-9.36L1 10" />
                </svg>
                Retry Artifact
              </button>
            </div>
          ) : (
            <img
              key={`${art.id}-${state.retryKey}`}
              src={url}
              alt={`${art.label} diagnostic artifact`}
              className={`artifact-image ${isLoading ? 'img-hidden' : 'img-visible'}`}
              onLoad={() => handleImageLoad(art.id)}
              onError={() => handleImageError(art.id)}
              loading="lazy"
            />
          )}
        </div>

        {isGrid && (
          <p className="grid-pane-desc">{art.description}</p>
        )}
      </div>
    );
  };

  return (
    <section className="result-viewer-card" aria-label="Registration Diagnostic Artifacts">
      {/* Header with Title and Mode Switchers */}
      <div className="result-viewer-header">
        <div className="viewer-title-group">
          <div className="viewer-badge-row">
            <span className="stage-b-pill">STAGE B VISUALIZER</span>
            <span className="viewer-id-tag">ID: {resultId}</span>
          </div>
          <h3 className="viewer-title">Registration Artifact Visual Diagnostics</h3>
          <p className="viewer-sub">
            Inspect warped output, SIFT correspondence pairs, MAGSAC++ inlier verification, and overlay alignment.
          </p>
        </div>

        <div className="viewer-controls">
          {/* Fit Mode Toggle */}
          <button
            type="button"
            className={`viewer-control-btn ${fitMode === 'contain' ? 'active' : ''}`}
            onClick={() => setFitMode((m) => (m === 'contain' ? 'original' : 'contain'))}
            title={fitMode === 'contain' ? 'Switch to 1:1 original resolution' : 'Fit to viewport'}
          >
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <path d="M8 3H5a2 2 0 0 0-2 2v3m18 0V5a2 2 0 0 0-2-2h-3m0 18h3a2 2 0 0 0 2-2v-3M3 16v3a2 2 0 0 0 2 2h3" />
            </svg>
            <span>{fitMode === 'contain' ? 'Fit Window' : 'Actual Size'}</span>
          </button>

          {/* View Mode Toggle (Tab vs 2x2 Grid) */}
          <div className="view-mode-toggle" role="radiogroup" aria-label="Visualizer View Mode">
            <button
              type="button"
              className={`toggle-mode-btn ${viewMode === 'tab' ? 'active' : ''}`}
              onClick={() => setViewMode('tab')}
              title="Single Tab Inspection View"
              aria-checked={viewMode === 'tab'}
              role="radio"
            >
              <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <rect width="18" height="18" x="3" y="3" rx="2" />
                <line x1="3" y1="9" x2="21" y2="9" />
              </svg>
              <span>Tabs</span>
            </button>
            <button
              type="button"
              className={`toggle-mode-btn ${viewMode === 'grid' ? 'active' : ''}`}
              onClick={() => setViewMode('grid')}
              title="2×2 Comparison Grid View"
              aria-checked={viewMode === 'grid'}
              role="radio"
            >
              <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <rect width="7" height="7" x="3" y="3" />
                <rect width="7" height="7" x="14" y="3" />
                <rect width="7" height="7" x="14" y="14" />
                <rect width="7" height="7" x="3" y="14" />
              </svg>
              <span>2×2 Grid</span>
            </button>
          </div>
        </div>
      </div>

      {/* Tabs Row (Only displayed in tab mode) */}
      {viewMode === 'tab' && (
        <div className="viewer-tabs-bar" role="tablist" aria-label="Artifact Tabs">
          {ARTIFACTS.map((art) => {
            const isCurrent = activeTab === art.id;
            const state = imageStates[art.id] || { status: 'loading' };
            return (
              <button
                key={art.id}
                id={`tab-${art.id}`}
                type="button"
                role="tab"
                aria-selected={isCurrent}
                aria-controls={`panel-${art.id}`}
                className={`viewer-tab-btn ${isCurrent ? 'tab-active' : ''} ${
                  state.status === 'error' ? 'tab-has-error' : ''
                }`}
                onClick={() => setActiveTab(art.id)}
              >
                <span className="tab-label-text">{art.label}</span>
                {state.status === 'loading' && <span className="tab-dot dot-loading" title="Loading image" />}
                {state.status === 'loaded' && <span className="tab-dot dot-loaded" title="Image loaded" />}
                {state.status === 'error' && <span className="tab-dot dot-error" title="Load error" />}
              </button>
            );
          })}
        </div>
      )}

      {/* Main Display Canvas */}
      <div className="viewer-canvas-area">
        {viewMode === 'tab' ? (
          <div
            id={`panel-${activeArtifact.id}`}
            role="tabpanel"
            aria-labelledby={`tab-${activeArtifact.id}`}
            className="tab-panel-wrapper"
          >
            {/* Tab Caption & Action Bar */}
            <div className="tab-caption-bar">
              <div className="tab-info-text">
                <div className="tab-heading-row">
                  <h4 className="tab-active-title">{activeArtifact.label}</h4>
                  <span className="tab-badge">{activeArtifact.badge}</span>
                </div>
                <p className="tab-description">{activeArtifact.description}</p>
              </div>

              <div className="tab-action-buttons">
                <a
                  href={getImageUrl(activeArtifact)}
                  target="_blank"
                  rel="noreferrer"
                  className="tab-action-btn"
                  title="Open full-resolution image in new browser tab"
                >
                  <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                    <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6" />
                    <polyline points="15 3 21 3 21 9" />
                    <line x1="10" y1="14" x2="21" y2="3" />
                  </svg>
                  <span>Open Full Res</span>
                </a>
                <a
                  href={getImageUrl(activeArtifact)}
                  download={`result_${resultId}_${activeArtifact.endpointType}.png`}
                  className="tab-action-btn primary"
                  title="Download artifact PNG"
                >
                  <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                    <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
                    <polyline points="7 10 12 15 17 10" />
                    <line x1="12" y1="15" x2="12" y2="3" />
                  </svg>
                  <span>Download PNG</span>
                </a>
              </div>
            </div>

            {/* Tab Artifact Image Viewport */}
            {renderImagePane(activeArtifact, false)}
          </div>
        ) : (
          /* 2x2 Grid Mode */
          <div className="grid-view-container" role="region" aria-label="All 4 Diagnostic Artifacts">
            {ARTIFACTS.map((art) => renderImagePane(art, true))}
          </div>
        )}
      </div>

      {/* Footer Diagnostic Context */}
      <div className="viewer-footer-meta">
        <div className="footer-meta-item">
          <span className="meta-label">Artifact Delivery:</span>
          <span className="meta-val">FastAPI StreamingResponse (PNG bytes)</span>
        </div>
        <div className="footer-meta-item">
          <span className="meta-label">Isolation Mode:</span>
          <span className="meta-val">Independent per-image fetch & retry</span>
        </div>
        {metrics?.timing?.visualization !== undefined && (
          <div className="footer-meta-item">
            <span className="meta-label">Render Latency:</span>
            <span className="meta-val">{metrics.timing.visualization.toFixed(4)}s</span>
          </div>
        )}
      </div>
    </section>
  );
}
